{{- range $name, $svc := .Values.externalServices }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
spec:
  type: {{ $svc.type }}
  selector:
{{ toYaml $svc.selector | indent 4 }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.targetPort }}
      nodePort: {{ $svc.nodePort }}
---
{{- end }}
{{- end }}
