{{- if .Values.serviceMonitors.nacos.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nacos-monitor-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: ruoyi
  password: "123456"
{{- end }}
