serviceMonitors:
  apisix:
    enabled: true
    namespace: apisix
    serviceLabelSelector:
      app.kubernetes.io/name: apisix
      app.kubernetes.io/service: apisix-prometheus-metrics
    endpoints:
      - port: prometheus
        path: /apisix/prometheus/metrics
        interval: 30s
        scrapeTimeout: 10s

  nacos:
    enabled: false

externalServices:
  grafana:
    enabled: false
    name: grafana-external
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30300
    selector: {}

  prometheus:
    enabled: false
    name: prometheus-external
    type: NodePort
    port: 9090
    targetPort: 9090
    nodePort: 30900
    selector: {}
