apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  labels:
    app.kubernetes.io/name: skywalking-ui
    app.kubernetes.io/part-of: observability-tracing
spec:
  selector:
    app.kubernetes.io/name: skywalking-ui
  ports:
    - name: http
      port: {{ .Values.skywalking.ui.service.port }}
      targetPort: http
