{{- if and .Values.global.serviceMonitor.enabled .Values.global.serviceMonitor.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.serviceMonitor.basicAuth.usernameSecret.name }}
type: Opaque
stringData:
  {{ .Values.global.serviceMonitor.basicAuth.usernameSecret.key }}: {{ .Values.global.serviceMonitor.basicAuth.credentials.username | quote }}
  {{ .Values.global.serviceMonitor.basicAuth.passwordSecret.key }}: {{ .Values.global.serviceMonitor.basicAuth.credentials.password | quote }}
{{- end }}
