apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ghv5/enterprise-cloud-lab.git
    targetRevision: main
    path: deploy/helm/blog-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ghv5/enterprise-cloud-lab.git
    targetRevision: main
    path: deploy/apisix
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ghv5/enterprise-cloud-lab.git
    targetRevision: main
    path: deploy/helm/blog-web
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
