{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-infra.mysql.fullname" . }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  mysql-user: {{ .Values.mysql.auth.username | quote }}
  mysql-password: {{ .Values.mysql.auth.password | quote }}
{{- end }}
