{{- if .Values.nacos.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-infra.nacos.fullname" . }}
type: Opaque
stringData:
  db-password: {{ .Values.nacos.database.password | quote }}
{{- end }}
