{{- if and .Values.nacos.enabled .Values.nacos.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-infra.nacos.fullname" . }}-external
  labels:
    app.kubernetes.io/name: nacos
    app.kubernetes.io/component: config-center
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.nacos.service.external.type }}
  selector:
    app.kubernetes.io/name: {{ include "platform-infra.nacos.fullname" . }}
  ports:
    - name: client
      port: {{ .Values.nacos.service.ports.client }}
      targetPort: client
      nodePort: {{ .Values.nacos.service.external.clientNodePort }}
{{- end }}
