FROM bellsoft/liberica-openjdk-rocky:17.0.16-cds
WORKDIR /app

COPY target/blog-api.jar /app/blog-api.jar

ENV PORT=8080
EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -fsS http://127.0.0.1:8080/actuator/health/liveness || exit 1

ENTRYPOINT ["java", "-jar", "/app/blog-api.jar"]
