apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  http:
    - name: argocd-root
      priority: 200
      websocket: true
      match:
        hosts:
          - argocd.localhost
        paths:
          - /*
      backends:
        - serviceName: argo-cd-argocd-server
          servicePort: 80
